name: brownhipp
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: derri <email@example.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  args: 'any'
  http_server: 'any'

transformers:
  - dart_to_js_script_rewriter